import { createClient } from '@supabase/supabase-js';
const SUPABASE_URL='https://cgkdztwtodmdteohvuoh.supabase.co';
const SUPABASE_KEY='sb_publishable_sULeDyfJ1l5xfuVhFgXRKA_bsim9qSe';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
let user=null,customers=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function getUser(){const {data,error}=await supabase.auth.getUser();if(error)throw error;user=data?.user||null;return user;}
async function load(){if(!user)await getUser();if(!user)return;const {data,error}=await supabase.from('qf_customers').select('id,business_name,ruc,active,created_at').eq('owner_id',user.id).order('business_name');if(error)throw error;customers=data||[];}
function render(){const target=document.querySelector('#content');if(!target)return;target.innerHTML=`<main class="qf-rec-page"><div class="qf-rec-titlebar"><div><h1>Clientes</h1><p>Administra los clientes de tus salidas y órdenes de compra.</p></div><button class="primary qf-client-new" type="button">+ Nuevo cliente</button></div><section class="qf-rec-kpis"><div class="qf-rec-card"><span>Clientes</span><strong>${customers.length}</strong></div><div class="qf-rec-card"><span>Activos</span><strong>${customers.filter(x=>x.active).length}</strong></div></section><section class="qf-rec-panel"><div class="qf-rec-panel-head"><h2>Clientes registrados</h2><span>${customers.length} registro(s)</span></div>${customers.length?`<div class="qf-rec-table-wrap"><table class="qf-rec-table"><thead><tr><th>Razón social / nombre</th><th>RUC</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${customers.map(c=>`<tr><td><b>${esc(c.business_name)}</b></td><td>${esc(c.ruc||'—')}</td><td><span class="qf-rec-status">${c.active?'Activo':'Inactivo'}</span></td><td><button type="button" class="secondary qf-client-edit" data-id="${esc(c.id)}">Editar</button> <button type="button" class="secondary qf-client-del" data-id="${esc(c.id)}">Eliminar</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="qf-rec-empty"><div class="qf-rec-empty-icon">👥</div><h3>Aún no hay clientes</h3><p>También puedes crear uno automáticamente al guardar una salida con un cliente nuevo.</p><button class="primary qf-client-first" type="button">+ Registrar primer cliente</button></div>`}</section></main>`;target.querySelector('.qf-client-new')?.addEventListener('click',()=>openForm());target.querySelector('.qf-client-first')?.addEventListener('click',()=>openForm());target.querySelectorAll('.qf-client-edit').forEach(b=>b.addEventListener('click',()=>openForm(b.dataset.id)));target.querySelectorAll('.qf-client-del').forEach(b=>b.addEventListener('click',()=>remove(b.dataset.id)));}
function openForm(id=null){const c=id?customers.find(x=>x.id===id):null;const modal=document.createElement('div');modal.className='qf-rec-modal';modal.innerHTML=`<div class="qf-rec-modal-card"><div class="qf-rec-modal-head"><div><h2>${c?'Editar cliente':'Nuevo cliente'}</h2><p>Datos básicos del cliente.</p></div><button type="button" class="qf-rec-close">×</button></div><form><div class="qf-rec-section"><div class="qf-rec-grid"><label class="wide">Razón social / nombre comercial<input name="business_name" required value="${esc(c?.business_name||'')}"></label><label>RUC<input name="ruc" maxlength="20" value="${esc(c?.ruc||'')}"></label><label>Estado<select name="active"><option value="true" ${c?.active!==false?'selected':''}>Activo</option><option value="false" ${c?.active===false?'selected':''}>Inactivo</option></select></label></div></div><div class="qf-rec-form-actions"><button type="button" class="secondary qf-rec-cancel">Cancelar</button><button class="primary" type="submit">${c?'Guardar cambios':'Guardar cliente'}</button></div></form></div>`;document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.qf-rec-close').onclick=close;modal.querySelector('.qf-rec-cancel').onclick=close;modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const business_name=String(f.get('business_name')||'').trim(),ruc=String(f.get('ruc')||'').trim()||null,active=f.get('active')==='true';if(!user)await getUser();if(!user)return;const result=id?await supabase.from('qf_customers').update({business_name,ruc,active}).eq('id',id).eq('owner_id',user.id):await supabase.from('qf_customers').insert({owner_id:user.id,business_name,ruc,active}).select('id').single();if(result.error){alert('No se pudo guardar el cliente: '+result.error.message);return;}modal.remove();await load();render();};}
async function remove(id){if(!user)await getUser();if(!user)return;if(!confirm('¿Eliminar este cliente? Se marcará como inactivo para no romper documentos relacionados.'))return;const {error}=await supabase.from('qf_customers').update({active:false}).eq('id',id).eq('owner_id',user.id);if(error){alert('No se pudo eliminar el cliente: '+error.message);return;}await load();render();}
window.qfOpenClientes=async()=>{try{await getUser();if(!user){alert('Inicia sesión para acceder a Clientes.');return;}await load();render();}catch(e){console.error('Clientes:',e);alert('No se pudo cargar Clientes: '+(e?.message||e));}};
