import { createClient } from '@supabase/supabase-js';
import { openMovimientoForm } from './qf-movimiento-form.js';

const supabase=createClient('https://cgkdztwtodmdteohvuoh.supabase.co','sb_publishable_sULeDyfJ1l5xfuVhFgXRKA_bsim9qSe');
let currentUser=null,receipts=[],suppliers=[];
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const num=v=>Number(v||0);
async function getUser(){const {data,error}=await supabase.auth.getUser();if(error)throw error;currentUser=data?.user||null;return currentUser}
async function load(){if(!currentUser)await getUser();if(!currentUser)return;const [r,s]=await Promise.all([supabase.from('qf_receipts').select('*').eq('owner_id',currentUser.id).order('receipt_date',{ascending:false}).order('receipt_time',{ascending:false}),supabase.from('qf_suppliers').select('*').eq('owner_id',currentUser.id).order('name')]);if(r.error)throw r.error;if(s.error)throw s.error;receipts=r.data||[];suppliers=s.data||[];if(!receipts.length)return;const {data,error}=await supabase.from('qf_receipt_items').select('*').in('receipt_id',receipts.map(x=>x.id)).order('created_at');if(error)throw error;const map=new Map();for(const i of data||[]){const a=map.get(i.receipt_id)||[];a.push(i);map.set(i.receipt_id,a)}receipts.forEach(x=>x.items=map.get(x.id)||[])}
function render(){const t=document.querySelector('#content');if(!t)return;const weight=receipts.reduce((a,r)=>a+num(r.total_weight_kg),0),pending=receipts.filter(r=>r.status==='Pendiente de revisión').length,providerCount=new Set(receipts.map(r=>r.supplier_name).filter(Boolean)).size;t.innerHTML=`<main class="qf-rec-page"><div class="qf-rec-titlebar"><div><h1>Entradas</h1><p>Ingreso de materiales, documentos y control de proveedores.</p></div><button class="primary qf-rec-new" type="button">+ Nueva entrada</button></div><section class="qf-rec-kpis"><div class="qf-rec-card"><span>Entradas</span><strong>${receipts.length}</strong></div><div class="qf-rec-card"><span>Peso recibido</span><strong>${weight.toLocaleString('es-PE')} kg</strong></div><div class="qf-rec-card"><span>Proveedores</span><strong>${providerCount}</strong></div><div class="qf-rec-card"><span>Pendientes de revisión</span><strong>${pending}</strong></div></section><section class="qf-rec-panel"><div class="qf-rec-panel-head"><h2>Entradas de materiales</h2><span>${receipts.length} registro(s)</span></div>${receipts.length?`<div class="qf-rec-table-wrap"><table class="qf-rec-table"><thead><tr><th>Fecha</th><th>Documento</th><th>Proveedor</th><th>OC</th><th>Peso</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${receipts.map(r=>`<tr><td>${esc(r.receipt_date)}</td><td><b>${esc(r.document_type||'Guía de Remisión')}</b><br>${esc([r.guide_series,r.guide_number].filter(Boolean).join('-')||'Sin número')}</td><td>${esc(r.supplier_name||'')}</td><td>${esc(r.purchase_order||'—')}</td><td>${num(r.total_weight_kg).toLocaleString('es-PE')} kg</td><td><span class="qf-rec-status">${esc(r.status||'')}</span></td><td><button class="secondary qf-rec-edit" type="button" data-id="${esc(r.id)}">Ver</button> <button class="secondary qf-rec-del" type="button" data-id="${esc(r.id)}">Eliminar</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="qf-rec-empty"><div class="qf-rec-empty-icon">📥</div><h3>Aún no hay entradas</h3><p>Registra aquí los documentos con los que los proveedores ingresan materiales a la planta.</p><button class="primary qf-rec-first" type="button">+ Registrar primera entrada</button></div>`}</section></main>`;t.querySelector('.qf-rec-new')?.addEventListener('click',()=>open(null));t.querySelector('.qf-rec-first')?.addEventListener('click',()=>open(null));t.querySelectorAll('.qf-rec-edit').forEach(b=>b.onclick=()=>open(b.dataset.id));t.querySelectorAll('.qf-rec-del').forEach(b=>b.onclick=()=>removeReceipt(b.dataset.id))}
async function open(id){try{if(!currentUser)await getUser();if(!currentUser){alert('Inicia sesión para acceder a Entradas.');return}await openMovimientoForm({mode:'entrada',record:id?receipts.find(x=>x.id===id):null,onSaved:async()=>{await load();render()}})}catch(e){console.error('Entradas:',e);alert('No se pudo abrir Entradas: '+(e?.message||e))}}
async function removeReceipt(id){if(!currentUser)await getUser();if(!currentUser)return;if(!confirm('¿Eliminar esta entrada y sus materiales?'))return;const {error}=await supabase.from('qf_receipts').delete().eq('id',id).eq('owner_id',currentUser.id);if(error){alert('No se pudo eliminar: '+error.message);return}await load();render()}
window.qfOpenRecepciones=async()=>{try{await getUser();if(!currentUser){alert('Inicia sesión para acceder a Entradas.');return}await load();render()}catch(error){console.error('Entradas:',error);alert('No se pudo cargar Entradas: '+(error?.message||error))}};
