import { createClient } from '@supabase/supabase-js';
import { openMovimientoForm } from './qf-movimiento-form.js';

const supabase=createClient('https://cgkdztwtodmdteohvuoh.supabase.co','sb_publishable_sULeDyfJ1l5xfuVhFgXRKA_bsim9qSe');
let user=null,shipments=[],customers=[];
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const num=v=>Number.isFinite(Number(v))?Number(v):0;

async function getUser(){const {data,error}=await supabase.auth.getUser();if(error)throw error;user=data?.user||null;return user}
async function load(){if(!user)await getUser();if(!user)return;const [s,c]=await Promise.all([
  supabase.from('qf_shipments').select('id,guide_number,guide_date,guide_time,document_type,reason,customer_id,purchase_order_id,origin,destination,gross_weight_kg,vehicle_id,driver_id,status,observations').eq('owner_id',user.id).order('guide_date',{ascending:false}).order('guide_time',{ascending:false}),
  supabase.from('qf_customers').select('id,business_name,ruc').eq('owner_id',user.id).eq('active',true).order('business_name')
]);if(s.error)throw s.error;if(c.error)throw c.error;shipments=s.data||[];customers=c.data||[];if(!shipments.length)return;const {data,error}=await supabase.from('qf_shipment_items').select('*').in('shipment_id',shipments.map(x=>x.id)).order('line_no');if(error)throw error;const map=new Map();for(const i of data||[]){const a=map.get(i.shipment_id)||[];a.push(i);map.set(i.shipment_id,a)}shipments.forEach(x=>x.items=map.get(x.id)||[])}
function render(){const t=document.querySelector('#content');if(!t)return;t.innerHTML=`<main class="qf-rec-page"><div class="qf-rec-titlebar"><div><h1>Salidas</h1><p>Despacho de productos, documentos y transporte.</p></div><button class="primary qf-rec-new" type="button">+ Nueva salida</button></div><section class="qf-rec-panel"><div class="qf-rec-panel-head"><h2>Salidas registradas</h2><span>${shipments.length} registro(s)</span></div>${shipments.length?`<div class="qf-rec-table-wrap"><table class="qf-rec-table"><thead><tr><th>Fecha</th><th>Documento</th><th>Cliente</th><th>Peso</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${shipments.map(x=>`<tr><td>${esc(x.guide_date)}</td><td><b>${esc(x.document_type||'Guía de Remisión')}</b><br>${esc(x.guide_number)}</td><td>${esc(customers.find(c=>c.id===x.customer_id)?.business_name||'')}</td><td>${num(x.gross_weight_kg).toLocaleString('es-PE')} kg</td><td><span class="qf-rec-status">${esc(x.status||'')}</span></td><td><button class="secondary qf-rec-edit" type="button" data-id="${esc(x.id)}">Ver</button> <button class="secondary qf-rec-del" type="button" data-id="${esc(x.id)}">Eliminar</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="qf-rec-empty"><h3>Aún no hay salidas</h3><p>Registra aquí los documentos de despacho.</p><button class="primary qf-rec-first" type="button">+ Registrar primera salida</button></div>`}</section></main>`;t.querySelector('.qf-rec-new')?.addEventListener('click',()=>open(null));t.querySelector('.qf-rec-first')?.addEventListener('click',()=>open(null));t.querySelectorAll('.qf-rec-edit').forEach(b=>b.onclick=()=>open(b.dataset.id));t.querySelectorAll('.qf-rec-del').forEach(b=>b.onclick=()=>remove(b.dataset.id))}
async function open(id){try{if(!user)await getUser();if(!user){alert('Inicia sesión para acceder a Salidas.');return}await openMovimientoForm({mode:'salida',record:id?shipments.find(x=>x.id===id):null,onSaved:async()=>{await load();render()}})}catch(e){console.error('Salidas:',e);alert('No se pudo abrir Salidas: '+(e?.message||e))}}
async function remove(id){if(!user)await getUser();if(!user)return;const {count,error}=await supabase.from('qf_inventory_movements').select('id',{count:'exact',head:true}).eq('shipment_id',id).eq('owner_id',user.id);if(error){alert('No se pudo verificar Inventario: '+error.message);return}if(count>0){alert('Esta salida está vinculada a Inventario y no se puede eliminar.');return}if(!confirm('¿Eliminar esta salida y sus materiales?'))return;const r=await supabase.from('qf_shipments').delete().eq('id',id).eq('owner_id',user.id);if(r.error){alert('No se pudo eliminar: '+r.error.message);return}await load();render()}
window.qfOpenSalidas=async()=>{try{await getUser();if(!user){alert('Inicia sesión para acceder a Salidas.');return}await load();render()}catch(e){console.error('Salidas:',e);alert('No se pudo cargar Salidas: '+(e?.message||e))}};
